### ISSUE TITLE
Error in pulling noise sample when no clicks

### ISSUE THREAD

**Issue by rcohen85** [MarineBioAcousticsRC/Triton#15]
In the spice-snr-threshold branch, in dt_parameters line 39 when there are no valid detections passed in (variable "clicks" is empty) then there are no indices to indicate a chunk of samples prior to any detections which could be saved as a noise sample. 
![image](https://user-images.githubusercontent.com/30301737/64449481-de9bcb00-d094-11e9-9895-0c2c0bb74a3c.png)

We could probably just skip all of dt_parameters if no valid detections were found.  Here's the fix I put in:
![image](https://user-images.githubusercontent.com/30301737/64449513-ef4c4100-d094-11e9-9379-ad34e1328b6b.png)

**Comment by kfrasier** [comment]
fixed 9/13
