### ISSUE TITLE
Batch run detections not matching Interactive detector results  

### ISSUE THREAD

**Issue by jstanley4** [MarineBioAcousticsRC/Triton#97]
Hi there,
When completing some performance evaluations on the vessel detector I noticed that the when using exactly the same settings in both the initial "interactive detector" and the subsequent "batch run detector" the results do not end up the same.
I assumed the "interactive detector" allowed you to best set your motion control settings and then when these are performing best you apply them to the "batch run detector". However, I have noticed some dropped detections in the batch detector.

Is this normal? Happy to share more details and examples if needed.
I initially worked with the ship detector for the SanctSound program  a couple of years back when working in the US - Alba gave me the first run though of the software :) 

Many Thanks

**Comment by asolsonaberga** [comment]
Hi Jenni,

The interactive detector face was designed to allow you to fine-tune the settings, and it can produce different results than the batch-run detector. The interactive detector only displays the detection results in that window. To detect ships at the edges of a window, the batch-run detector uses a moving window decision. It compares the results of three windows that overlap during the time specified in your settings. In my case, I had 1-hour windows with a 30-minute overlap. For example, one window will go from 6 a.m. to 7 a.m., the next one from 6:30 a.m. to 7:30 a.m., and the third from 7 a.m. to The batch-run detector will compare the decisions from these three windows and assign the label that matches on at least two of them.

I can point you to the section of code where these decisions are made if you need it, but you could test this in the interactive detector by looking at the decisions of three consecutive windows that overlap by the amount you specified.

Please let me know if you have any additional questions.

Alba

**Comment by jstanley4** [comment]
Hi Alba! Nice to talk to you, wasn't sure if you would still be helping with questions on this :)
I was seriously thinking of emailing you to ask the question but didn't want to bother you.

OK, so I think it might me an edge of the window problem then possibly. 
What I was seeing was that the interactive detector was "detecting" more vessels than the batch detector when comparing say a couple of days. So the settings were working to detect them initially (in the interactive part), but then when I put the same settings in the batch detector some vessels would get left out. 
I will play with the window and overlap a little more and see if that changes it. In this instance, I was using 2 hour windows with a 1.5 sliding time, which is quite a bit of overlap right? I think I tried a 0.5 sliding time too but it didn't make a difference. I am pretty sure that it was labelled a vessel in at least two windows also, but I will double check and play with the window size and see if it helps :)
Thanks for the info
Jenni

**Comment by jstanley4** [comment]
Hi Alba,

I am still struggling to get some vessels that are detected as vessel in the interactive detector to be labeled as anything, either vessel or ambient, in the batch detector. 
Do you think this can be remedied by changing way the decisions are made in the code? IF you could point me to where that part is I can take a look. I have had a little look but there is a lot of code and I may have just skimmed over it.

Thanks,

Jenni

**Comment by asolsonaberga** [comment]
Hi Jenni,

The script that has all the code dealing with the decisions between the overlapping windows is in the folder detections/sh_detector_batch.m

In lines 35-62, the detector is implemented in each sliding window.
In lines 66-122, the detections of the overlapping windows are compared, and specifically at lines 106-121 is where the decision are taken to prioritize the labels that are more frequent if classification do not match between the 3 overlapping windows.

Please let me know if you have any additional questions.

Alba

**Comment by jstanley4** [comment]
Hi Alba,

Just working through your suggestions above - thanks for that.
However, when comparing some runs, I was trying to use the "Visualize detections" via the "load labels" in the menu, however, I keep running into this error as soon as I try to jump to the next window. Any ideas? Seems like a time issue.
I can't remember if I have ever used this before and whether it worked or not in the past.

Brace indexing is not supported for variables of this type.

Error in sh_date_to_xaxis>timeIndexBin (line 63)
      files = sprintf('%s ', PARAMS.ltsahd.fname{rawIndex});

Error in sh_date_to_xaxis (line 20)
[startFile, startIdx] = timeIndexBin(start);

Error in sh_plot_labels>plot_times (line 83)
    Offsets = sh_date_to_xaxis([StartDate; StopDate]);

Error in sh_plot_labels (line 17)
    plot_times(REMORA.sh.detection.starts,REMORA.sh.detection.stops,...

Error in sh_control_visLabel (line 88)
    sh_plot_labels
 
Error while evaluating UIControl Callback.


Many Thanks,

Jenni

**Comment by asolsonaberga** [comment]
Hi Jenni,

Could you give me more information?
For example:
- Are you uploading the.tlab files created with the batch run detector?
- Do you have all the Triton windows open?
- What kind of audio data are you using .xwav or .wav, and so do you have
the LTSA files computed?

Best,

Alba
