### ISSUE TITLE
Ship Detector - Always Removing Disk-Write Noise, with simple fix

### ISSUE THREAD

**Issue by kmerkens** [MarineBioAcousticsRC/Triton#99]
Hi Triton team,

The Ship Detector has a check-box button to select whether one wants to exclude Disk Write noise, which is very helpful for HARP data, but not much else. It looks like the way it is coded (Lines 28-38 in sh_passage_detector.m) it always functions to remove the "Disk-Write" noise, even if the box is unchecked. A simple fix would be to change line 28 to read: if REMORA.sh.settings.diskWrite == 1, which is the value of REMORA.sh.settings.diskWrite if the checkbox is clicked. (If the check box is unchecked the value of REMORA.sh.settings.diskWrite is "Exclude Disk-Write Noise", which still exists, so the current code considers this to also mean that one should remove the Disk Writes.)

-Karli

https://github.com/MarineBioAcousticsRC/Triton/blob/0ae8a7fca95e035991e8f450461c3b8a23c4f9cf/Remoras/Ship-Detector/detection/sh_passage_detector.m#L28

**Comment by asolsonaberga** [comment]
Thank you Karlina, I have implemented the changes as you suggested.
